SELECT 
 PV.COD_EMPRESA,
 PV.COD_PRODUTO,
 P.DESCRICAO,
 P.COD_UNIDADE,
 PR.COD_FAMILIA_ACCAD,
 PR.COD_GRUPO_ACCAD,
 PR.COD_SUB_GRUPO_ACCAD,
 PR.CURVA_ABC,
 RETORNA_SALDO_ESTOQUE_ITEM (PV.COD_EMPRESA, PV.COD_PRODUTO) AS SALDO_ESTOQUE 
 FROM PRODUTOS_MOVIMENTO PV 
 LEFT JOIN PRODUTOS P ON PV.COD_PRODUTO = P.COD_PRODUTO
 LEFT JOIN PRODUTOS_PRIMARIOS PR ON PR.COD_PRODUTO = PV.COD_PRODUTO
 LEFT JOIN ALMOXARIFADO_END AE ON PV.COD_PRODUTO = AE.COD_PRODUTO
 WHERE (PV.COD_EMPRESA = :COD_EMPRESA)  AND (TRUNC(PV.DATA_MOVIMENTO) <=:DATAMOVIMENTO) AND (PV.SITUACAO = 'A') AND (AE.RUA IS NULL) AND (AE.BLOCO IS NULL) AND (AE.NIVEL IS NULL) AND (AE.GAVETA IS NULL) AND (AE.POSICAO IS NULL)   
 GROUP BY
 PV.COD_EMPRESA,
 PV.COD_PRODUTO,
 P.DESCRICAO,
 P.COD_UNIDADE,
 PR.COD_FAMILIA_ACCAD,
 PR.COD_GRUPO_ACCAD,
 PR.COD_SUB_GRUPO_ACCAD,
 PR.CURVA_ABC;